apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "backend.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from Frontend
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "backend.fullname" . | replace "backend" "frontend" }}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # Allow egress to MySQL
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "backend.fullname" . | replace "backend" "database" }}-mysql
      ports:
        - protocol: TCP
          port: 3306
    # Allow egress to Redis
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "backend.fullname" . | replace "backend" "database" }}-redis
      ports:
        - protocol: TCP
          port: 6379
    # Allow egress to Frontend (as requested)
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "backend.fullname" . | replace "backend" "frontend" }}
      ports:
        - protocol: TCP
          port: 8080
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
