apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app: {{ include "database.fullname" . }}-mysql
spec:
  clusterIP: None  # Headless service
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: {{ include "database.fullname" . }}-mysql
