apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app: {{ include "database.fullname" . }}-redis
spec:
  clusterIP: None  # Headless service
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app: {{ include "database.fullname" . }}-redis
