apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "database.fullname" . }}-redis
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app: {{ include "database.fullname" . }}-redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "database.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "database.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "database.fullname" . }}-redis-pvc
